server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://20.45.0.9:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/user/**